Feature/employment history
L1ght-time/my-portfolio-next-ts pull request #22
Opened 2023-03-04 12:02 UTC by L1ght-time

2023-03-04 19:33 UTC, mykyta-lazurenko requested changes

2023-03-04 19:33 UTC, mykyta-lazurenko commented on src/components/shared/Card/Card.tsx
> +const CardContext = createContext(null);
For what?

2023-03-04 19:33 UTC, mykyta-lazurenko commented on src/pages/about/EmploymentHistory/EmploymentHistory.types.ts
> +  item: string;
Don't use 'item', 'data', etc.. 
Write 'company', 'profile', more understanding

2023-03-04 19:33 UTC, mykyta-lazurenko commented on src/pages/about/index.tsx
>      const response = await fetch(`${process.env.API_HOST}/about`);
Use ky

2023-03-04 19:33 UTC, mykyta-lazurenko commented on src/pages/api/db/about.ts
> +}
Indent

2023-03-04 19:33 UTC, mykyta-lazurenko commented on src/pages/api/db/about.ts
> +        id: 0,
Move image here

2023-03-04 19:33 UTC, mykyta-lazurenko commented on src/pages/about/EmploymentHistory/EmploymentHistory.tsx
> +import civenty from '@/assets/civenty.jpeg';
Move that to the model, components do not need static if you can move in mapping

2023-03-04 19:33 UTC, mykyta-lazurenko commented on src/pages/about/EmploymentHistory/EmploymentHistory.types.ts
> +export default interface IEmploymentHistoryProps {
Default? Its model won’t extend?

2023-03-04 19:33 UTC, mykyta-lazurenko commented on src/pages/about/EmploymentHistory/EmploymentHistory.types.ts
> +export default interface IEmploymentHistoryProps {
I think better use naming export

2023-03-04 19:33 UTC, mykyta-lazurenko commented on src/pages/about/index.tsx
> +        title,
Title - static, remove from model

2023-03-04 19:33 UTC, mykyta-lazurenko commented on src/pages/about/index.tsx
>  }
Indent

2023-03-04 19:33 UTC, mykyta-lazurenko commented on src/pages/about/index.tsx
> +  console.log({ title, employmentHistory });
Logs

2023-03-04 19:33 UTC, mykyta-lazurenko commented on src/pages/about/index.tsx
> +        <h2>Employment History:</h2>
Locale

2023-03-04 19:33 UTC, mykyta-lazurenko commented on src/pages/about/EmploymentHistory/EmploymentHistory.tsx
> +        <p>Skills:</p>
The same

2023-03-06 19:48 UTC, L1ght-time commented on src/components/shared/Card/Card.tsx
> +const CardContext = createContext(null);
May be for theme

2023-03-06 20:23 UTC, L1ght-time commented on src/pages/about/index.tsx
>  }
lint doesn't low me do it.

2023-03-07 15:55 UTC, mykyta-lazurenko commented on src/components/shared/Card/Card.tsx
> +const CardContext = createContext(null);
I don't think that's necessary right now.

2023-03-07 21:51 UTC, mykyta-lazurenko commented on src/components/shared/Card/CardBadge/CardBadge.types.ts
> +export type TCardBadgeProps = PropsWithChildren<JSX.IntrinsicElements['span']>;
```suggestion
export type TCardBadgeProps = JSX.IntrinsicElements['span'];
```

2023-03-07 21:52 UTC, mykyta-lazurenko commented on src/components/shared/Card/CardBody/CardBody.types.ts
> +export type TCardBodyProps = PropsWithChildren<JSX.IntrinsicElements['div']>;
```suggestion
export type TCardBodyProps = JSX.IntrinsicElements['div'];
```

2023-03-07 21:53 UTC, mykyta-lazurenko commented on src/components/shared/Card/CardImage/CardImage.types.ts
> +import { ImageProps } from 'next/dist/client/image';
```suggestion
import { ImageProps } from 'next/image';
```

2023-03-07 21:54 UTC, mykyta-lazurenko commented on src/components/shared/Card/CardButton/CardButton.types.ts
> +export type CardButtonProps = PropsWithChildren<JSX.IntrinsicElements['button']>;
```suggestion
export type CardButtonProps = JSX.IntrinsicElements['button'];
```

2023-03-07 21:54 UTC, mykyta-lazurenko commented on src/components/shared/Card/CardText/CardText.types.ts
> +export type TCardTextProps = PropsWithChildren<JSX.IntrinsicElements['p']>;
```suggestion
export type TCardTextProps = JSX.IntrinsicElements['p'];
```

2023-03-07 22:12 UTC, mykyta-lazurenko requested changes

2023-03-07 22:12 UTC, mykyta-lazurenko commented on src/components/shared/Card/CardWrapper/CardWrapper.tsx
> +export const CardWrapper: FC<TCardWrapperProps> = ({ children, ...rest }) => <div {...rest}>{children}</div>;
Useless component

2023-03-07 22:12 UTC, mykyta-lazurenko commented on src/components/shared/Card/index.ts
> +export { CardText } from './CardText';
Useless components

2023-03-07 22:12 UTC, mykyta-lazurenko commented on src/components/shared/Title/Title.tsx
> +    <Heading className={className} {...rest}>
```suggestion
    <Heading {...rest}>
```

2023-03-07 22:12 UTC, mykyta-lazurenko commented on src/components/shared/Title/Title.types.ts
> +export type TTitleProps = THeading & PropsWithChildren<JSX.IntrinsicElements[THeading['headingLevel']]>;
```suggestion
type THeading = { as: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' };

export type TTitleProps = THeading & JSX.IntrinsicElements[THeading['as']];
```

2023-03-07 22:12 UTC, mykyta-lazurenko commented on src/components/shared/Title/Title.tsx
> +export const Title: FC<TTitleProps> = ({ headingLevel, children, className, ...rest }) => {
But I think it's a useless component

2023-03-09 14:10 UTC, mykyta-lazurenko approved these changes

2023-03-09 14:10 UTC, mykyta-lazurenko commented on package.json
> +    "ky": "^0.33.2",
Remove

2023-03-09 14:10 UTC, mykyta-lazurenko commented on src/components/pages/About/About.tsx
> +const fetcher = (...args: any[]) => fetch(...(args as [any, any])).then((res) => res.json());
Move to global constants

2023-03-09 14:10 UTC, mykyta-lazurenko commented on src/components/pages/About/About.tsx
> +  const { data: about } = useSWR<IAboutData>('/api/about', fetcher);
Better move to `useAbout` hook

2023-03-09 14:10 UTC, mykyta-lazurenko commented on src/components/pages/About/EmploymentHistory/helper/getDiffPeriod.ts
> +};
Localization?

2023-03-09 14:10 UTC, mykyta-lazurenko commented on src/components/pages/About/EmploymentHistory/helper/getDiffPeriod.ts
> +export const getAmountOfPeriod = ({ months }: IDiffPeriodProps): string | null => {
Here needs only `months`, remove the object notation

2023-03-09 14:16 UTC, merged

2023-03-09 14:16 UTC, L1ght-time commented
I will fix the comments in the next PR.