Feature/should add internationalization
L1ght-time/my-portfolio-next-ts pull request #6
Opened 2023-02-21 15:10 UTC by L1ght-time

2023-02-21 16:53 UTC, mykyta-lazurenko requested changes

2023-02-21 16:53 UTC, mykyta-lazurenko commented on src/components/Layout/NavBar/LanguageDropdown/LanguageDropdown.constants.ts
>  ];
```suggestion
] as const;
```

2023-02-21 16:53 UTC, mykyta-lazurenko commented on src/components/Layout/NavBar/LanguageDropdown/LanguageDropdown.tsx
> +  const handleClick = (name: string) => {
`useCallback`

2023-02-21 16:53 UTC, mykyta-lazurenko commented on src/components/Layout/NavBar/LanguageDropdown/LanguageDropdown.tsx
> +    setLocale(LOCALES[name.toUpperCase() as keyof typeof LOCALES]);
Move this logic in `useLayoutStore()`, when changing locales we need both functions. Could you combine `setLanguage` and `setLocale`?

2023-02-21 16:53 UTC, mykyta-lazurenko commented on src/components/Layout/NavBar/LanguageDropdown/LanguageDropdown.tsx
> +    setLocale(LOCALES[name.toUpperCase() as keyof typeof LOCALES]);
`keyof typeof LOCALES` move to type `LocalesKeys` near locales and import here.

2023-02-21 16:53 UTC, mykyta-lazurenko commented on src/components/Layout/NavBar/LanguageDropdown/constants.ts
> +};
Better use camelCase for keys

2023-02-21 16:53 UTC, mykyta-lazurenko commented on src/components/Layout/NavBar/LanguageDropdown/constants.ts
> +};
```suggestion
export const LANGUAGES = {
  ENGLISH: 'ENGLISH',
  UKRAINE: 'UKRAINE',
} as const;
```

2023-02-21 16:53 UTC, mykyta-lazurenko commented on src/i18n/I18nProvider/I18nProvider.types.ts
> +export type TProvider = PropsWithChildren & { locale: keyof typeof LOCALES };
reuse `keyof typeof LOCALES` after creating type `LocalesKeys`

2023-02-21 16:53 UTC, mykyta-lazurenko commented on src/i18n/I18nProvider/I18nProvider.types.ts
> +export type TProvider = PropsWithChildren & { locale: keyof typeof LOCALES };
It's props for `IntlProvider`, inherit him props.

2023-02-21 16:53 UTC, mykyta-lazurenko commented on src/i18n/I18nProvider/I18nProvider.tsx
> +  <IntlProvider textComponent={Fragment} locale={locale} messages={messages[locale]}>
After update `TProvider` type you can use rest and spread operators like that:

```suggestion
export const I18nProvider = ({ children, locale, ...props }: TProvider) => (
  <IntlProvider textComponent={Fragment} locale={locale} messages={messages[locale]} {...props} >
```

2023-02-21 16:53 UTC, mykyta-lazurenko commented on src/store/layoutStore.ts
>    setOpen: () => set((state: IStore) => ({ isOpen: !state.isOpen })),
It's toggle open, better rename to `toggleOpen`

2023-02-21 16:53 UTC, mykyta-lazurenko commented on src/i18n/constants.ts
> +};
Better use camelCase for keys.

2023-02-21 16:53 UTC, mykyta-lazurenko commented on src/i18n/constants.ts
> +};
In most cases, locale keys save as 2 letters, like `en`, `ru`, `ua`, `it`.

2023-02-21 16:53 UTC, mykyta-lazurenko commented on src/pages/_app.tsx
> +    <I18nProvider locale={locale as keyof typeof LOCALES}>
Remove `as` operator

2023-02-21 16:53 UTC, mykyta-lazurenko commented on src/store/layoutStore.ts
> +  locale: string;
It's not `string`, it's a literals union

2023-02-21 16:53 UTC, mykyta-lazurenko commented on src/store/layoutStore.ts
> +  setLocale: (value: string) => void;
`value` isn't `string`, it's a literals union

2023-02-21 16:53 UTC, mykyta-lazurenko commented on src/store/layoutStore.ts
> +    set((state: IStore) => ({
You do not use `state`, remove him.
```suggestion
    set(() => ({
```

2023-02-21 16:53 UTC, mykyta-lazurenko commented on src/store/layoutStore.ts
>      set((state: IStore) => ({
You do not use `state`, remove him.

2023-02-21 16:53 UTC, mykyta-lazurenko commented on src/store/layoutStore.ts
> +  locale: LOCALES.ENGLISH,
What is the difference between the keys `locale` and `language`?

2023-02-21 16:53 UTC, mykyta-lazurenko commented on src/i18n/helpers/translate.tsx
> +export const translate = (id: string, value = {}) => <FormattedMessage id={id} values={{ ...value }} />;
It's a component, not a helper, he returns `jsx`.

2023-02-21 16:53 UTC, mykyta-lazurenko commented on src/i18n/helpers/translate.tsx
> +export const translate = (id: string, value = {}) => <FormattedMessage id={id} values={{ ...value }} />;
You can use `formattedMessage` from `react-intl` instead.

2023-02-23 13:48 UTC, L1ght-time commented on src/components/Layout/NavBar/LanguageDropdown/LanguageDropdown.tsx
> +  const handleClick = (name: string) => {
I don't use handleClick anymore.

2023-02-23 14:16 UTC, mykyta-lazurenko requested changes

2023-02-23 14:16 UTC, mykyta-lazurenko commented on src/store/layoutStore.ts
> +  setToggleOpen: () => void;
```suggestion
toggleOpen: () => void;
```

2023-02-23 14:16 UTC, mykyta-lazurenko commented on src/store/layoutStore.ts
> +  toggleOpen: boolean;
```suggestion
  isOpen: boolean;
```

2023-02-23 14:16 UTC, mykyta-lazurenko commented on src/pages/_app.tsx
> +  const { locale } = useLayoutStore();
Move to `I18nProvider`

2023-02-23 15:04 UTC, mykyta-lazurenko approved these changes

2023-02-23 15:10 UTC, merged